/-
  POUNCE Lean certificate — generated proof (local strict minimum, Putinar SOS).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = local-min-strict
  problem_class = sos-poly
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Certifies  γ ≤ p(x)  at every FEASIBLE x WITHIN THE BALL below, with γ = -2,
  via  p(x) − γ − μ·‖x − x*‖² = σ₀(x) + Σᵢ σᵢ(x)·gᵢ(x) + σ_B(x)·(r² − ‖x − c‖²)
  and every σ a PSD Gram form. The bound holds on that set only — weaker
  than an unconstrained SOS bound, and also far more widely available:
  `p − γ` need only be a sum of squares MODULO the constraints.

  The ball is a constraint like any other here; nothing about the proof
  knows it is a neighborhood. What that buys is reach: at a local
  minimum that is not global the unrestricted claim is FALSE, so no
  certificate for it exists at any relaxation order, while restricted
  to the ball the claim is both true and easier to certify.

  The bound is ATTAINED at the exhibited xstar, itself proved to lie in
  the set the bound is about, so it is the local minimum.

  And STRICTLY so: the shifted identity certifies growth at rate μ = 2,
  i.e. p(x) ≥ p(x*) + μ·‖x − x*‖², so no other point of the region ties.
  This is what the second-order sufficient conditions are for, reached
  without them — and with the modulus exhibited, which SOSC leaves
  existential.
-/
import Mathlib
import PounceLean.PSD
import PounceLean.SOS

namespace PounceLean.CertifySOSBoxStrict

open Matrix
open PounceLean.SOS (sos_nonneg sqdist local_growth_of_sos strict_local_min_of_sos_growth)

set_option maxHeartbeats 0
set_option maxRecDepth 100000

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "22cdfc2a68dad5764d1f81e5f22906559b51085e2d75586e55108668caaa8d3e"
def solSha256 : String := "aeeeb077aa4b2c00da4d5bfc8497a03cd8502146880bc55383da70d23901c7b3"

/-- Objective (cert.problem.polynomial), possibly nonconvex. -/
def p (x : Fin 1 → ℚ) : ℚ := (-3) * (x 0) ^ 1 + (x 0) ^ 3

/-- The feasible set `gᵢ(x) ≥ 0` (cert.problem.poly_constraints). -/
def g : Fin 2 → (Fin 1 → ℚ) → ℚ := ![fun x => (x 0) ^ 1, fun x => (3) + (-1) * (x 0) ^ 1]

/-- Centre of the neighborhood the claim is about (cert.problem.neighborhood). -/
def center : Fin 1 → ℚ := ![1]

/-- Its radius, SQUARED — ℚ is not closed under square roots. -/
def rsq : ℚ := 1

/-- The ball is not a point: without this the claim below would hold
vacuously wherever `rsq < 0`, and say nothing where `rsq = 0`. -/
theorem radius_pos : (0:ℚ) < rsq := by norm_num [rsq]

/-- The growth modulus (cert.growth_modulus): the rate at which the
objective climbs away from the minimizer. Untrusted like every other
witness — too large a μ simply leaves the identity below unprovable. -/
def mu : ℚ := 2

/-- Positive, which is the whole of what makes the growth bound STRICT:
at μ = 0 it degenerates to the ordinary local-minimum claim. -/
theorem growth_pos : (0:ℚ) < mu := by norm_num [mu]

/-- The candidate minimizer (cert.candidate.x), and the point growth is
measured from; untrusted, checked below. -/
def xstar : Fin 1 → ℚ := ![1]

-- σ₀ — the bare square. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon0 (x : Fin 1 → ℚ) : Fin 3 → ℚ := ![1, (x 0) ^ 1, (x 0) ^ 2]
def G0 : Matrix (Fin 3) (Fin 3) ℚ := !![0, 0, 0; 0, 0, 0; 0, 0, 0]
def L0 : Matrix (Fin 3) (Fin 3) ℚ := !![1, 0, 0; 0, 1, 0; 0, 0, 1]
def D0 : Fin 3 → ℚ := ![0, 0, 0]

theorem hG0 : G0.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G0 L0 D0
  · intro i; fin_cases i <;> simp [D0] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G0, L0, D0, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

-- σ1, multiplying g 0. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon1 (x : Fin 1 → ℚ) : Fin 2 → ℚ := ![1, (x 0) ^ 1]
def G1 : Matrix (Fin 2) (Fin 2) ℚ := !![1, -1; -1, 1]
def L1 : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; -1, 1]
def D1 : Fin 2 → ℚ := ![1, 0]

theorem hG1 : G1.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G1 L1 D1
  · intro i; fin_cases i <;> simp [D1] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G1, L1, D1, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

-- σ2, multiplying g 1. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon2 (x : Fin 1 → ℚ) : Fin 2 → ℚ := ![1, (x 0) ^ 1]
def G2 : Matrix (Fin 2) (Fin 2) ℚ := !![0, 0; 0, 0]
def L2 : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; 0, 1]
def D2 : Fin 2 → ℚ := ![0, 0]

theorem hG2 : G2.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G2 L2 D2
  · intro i; fin_cases i <;> simp [D2] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G2, L2, D2, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

-- σ_B, multiplying the ball `rsq - sqdist x center`. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon3 (x : Fin 1 → ℚ) : Fin 2 → ℚ := ![1, (x 0) ^ 1]
def G3 : Matrix (Fin 2) (Fin 2) ℚ := !![0, 0; 0, 0]
def L3 : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; 0, 1]
def D3 : Fin 2 → ℚ := ![0, 0]

theorem hG3 : G3.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G3 L3 D3
  · intro i; fin_cases i <;> simp [D3] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G3, L3, D3, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- The bare square `σ₀`, as its Gram form. -/
def sigma0 (x : Fin 1 → ℚ) : ℚ := (mon0 x) ⬝ᵥ (G0 *ᵥ (mon0 x))

/-- The localizing multipliers, `sigma i` pairing with `g i`. -/
def sigma : Fin 2 → (Fin 1 → ℚ) → ℚ := ![fun x => (mon1 x) ⬝ᵥ (G1 *ᵥ (mon1 x)), fun x => (mon2 x) ⬝ᵥ (G2 *ᵥ (mon2 x))]

/-- `σ_B`, the ball's multiplier. -/
def sigmaB (x : Fin 1 → ℚ) : ℚ := (mon3 x) ⬝ᵥ (G3 *ᵥ (mon3 x))

theorem hsigma0 : ∀ x, 0 ≤ sigma0 x := sos_nonneg G0 mon0 hG0

theorem hsigma : ∀ i x, 0 ≤ sigma i x := by
  intro i
  fin_cases i
  · exact sos_nonneg G1 mon1 hG1
  · exact sos_nonneg G2 mon2 hG2

theorem hsigmaB : ∀ x, 0 ≤ sigmaB x := sos_nonneg G3 mon3 hG3

/-- The Putinar identity — on the SHIFTED objective, which is the whole
of the strict construction. `ring` closes it in the free variable `x`. -/
theorem sos_identity : ∀ x, p x - (-2) - mu * sqdist x xstar = sigma0 x + (∑ i, sigma i x * g i x) + sigmaB x * (rsq - sqdist x center) := by
  intro x
  simp only [p, g, sigma0, sigma, mon0, mon1, mon2, mon3, G0, G1, G2, G3, sigmaB, sqdist, center, rsq, mu, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]
  ring

/-- `xstar` is in the feasible set — the half a bound alone never gives. -/
theorem xstar_feasible : ∀ i, 0 ≤ g i xstar := by
  intro i
  fin_cases i <;> norm_num [g, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

/-- …and inside the ball. A point that attains the bound from outside
the neighborhood would say nothing about the neighborhood. -/
theorem xstar_in_ball : sqdist xstar center ≤ rsq := by
  norm_num [sqdist, xstar, center, rsq, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

/-- The bound is attained here — an equation over ℚ, with no tolerance. -/
theorem attains : p xstar = (-2) := by
  norm_num [p, xstar]

/-- Certified QUADRATIC GROWTH on the feasible set intersected with the
ball: the objective climbs at least at rate μ away from xstar. This is
the quantitative statement; the strict inequality below reads off it. -/
theorem local_growth : ∀ x : Fin 1 → ℚ, (∀ i, 0 ≤ g i x) → sqdist x center ≤ rsq → p xstar + mu * sqdist x xstar ≤ p x :=
  local_growth_of_sos p (-2) mu g sigma sigma0 sigmaB center rsq xstar
    hsigma0 hsigma hsigmaB sos_identity attains

/-- Certified STRICT LOCAL minimum (cert.verdict): every OTHER point of
the neighborhood is strictly worse, by at least μ·‖x − xstar‖². A plain
local-minimum certificate cannot say this — its `p xstar ≤ p x` is
equally true of a tie — and the usual route to it is the second-order
sufficient conditions, which this reaches without Taylor expansion, a
constraint qualification, or leaving ℚ. -/
theorem local_min_strict : ((∀ i, 0 ≤ g i xstar) ∧ sqdist xstar center ≤ rsq) ∧
    ∀ x : Fin 1 → ℚ, (∀ i, 0 ≤ g i x) → sqdist x center ≤ rsq →
      (p xstar + mu * sqdist x xstar ≤ p x) ∧ (x ≠ xstar → p xstar < p x) :=
  strict_local_min_of_sos_growth p (-2) mu g sigma sigma0 sigmaB center rsq xstar
    growth_pos hsigma0 hsigma hsigmaB sos_identity xstar_feasible xstar_in_ball
    attains

end PounceLean.CertifySOSBoxStrict
