/-
  POUNCE Lean certificate — generated proof (constrained minimum, Putinar SOS).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = global-min
  problem_class = sos-poly
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Certifies  γ ≤ p(x)  at every FEASIBLE x, with γ = -2, via
  p(x) − γ = σ₀(x) + Σᵢ σᵢ(x)·gᵢ(x) and every σ a PSD Gram form. The bound
  holds on the feasible set only — that is weaker than an unconstrained
  SOS bound and also far more widely available: `p − γ` need only be a sum
  of squares MODULO the constraints.

  The bound is ATTAINED at the exhibited xstar, which is itself proved
  feasible, so it is the constrained global minimum.
-/
import Mathlib
import PounceLean.PSD
import PounceLean.SOS

namespace PounceLean.CertifySOSBox

open Matrix
open PounceLean.SOS (sos_nonneg constrained_lower_bound_of_sos constrained_min_of_sos_attained)

set_option maxHeartbeats 0
set_option maxRecDepth 100000

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "22cdfc2a68dad5764d1f81e5f22906559b51085e2d75586e55108668caaa8d3e"
def solSha256 : String := "aeeeb077aa4b2c00da4d5bfc8497a03cd8502146880bc55383da70d23901c7b3"

/-- Objective (cert.problem.polynomial), possibly nonconvex. -/
def p (x : Fin 1 → ℚ) : ℚ := (-3) * (x 0) ^ 1 + (x 0) ^ 3

/-- The feasible set `gᵢ(x) ≥ 0` (cert.problem.poly_constraints). -/
def g : Fin 2 → (Fin 1 → ℚ) → ℚ := ![fun x => (x 0) ^ 1, fun x => (3) + (-1) * (x 0) ^ 1]

-- σ₀ — the bare square. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon0 (x : Fin 1 → ℚ) : Fin 3 → ℚ := ![1, (x 0) ^ 1, (x 0) ^ 2]
def G0 : Matrix (Fin 3) (Fin 3) ℚ := !![1 / 2, -1 / 2, 0; -1 / 2, 1 / 2, 0; 0, 0, 0]
def L0 : Matrix (Fin 3) (Fin 3) ℚ := !![1, 0, 0; -1, 1, 0; 0, 0, 1]
def D0 : Fin 3 → ℚ := ![1 / 2, 0, 0]

theorem hG0 : G0.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G0 L0 D0
  · intro i; fin_cases i <;> simp [D0] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G0, L0, D0, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

-- σ1, multiplying g 0. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon1 (x : Fin 1 → ℚ) : Fin 2 → ℚ := ![1, (x 0) ^ 1]
def G1 : Matrix (Fin 2) (Fin 2) ℚ := !![3 / 2, -3 / 2; -3 / 2, 3 / 2]
def L1 : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; -1, 1]
def D1 : Fin 2 → ℚ := ![3 / 2, 0]

theorem hG1 : G1.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G1 L1 D1
  · intro i; fin_cases i <;> simp [D1] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G1, L1, D1, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

-- σ2, multiplying g 1. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon2 (x : Fin 1 → ℚ) : Fin 2 → ℚ := ![1, (x 0) ^ 1]
def G2 : Matrix (Fin 2) (Fin 2) ℚ := !![1 / 2, -1 / 2; -1 / 2, 1 / 2]
def L2 : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; -1, 1]
def D2 : Fin 2 → ℚ := ![1 / 2, 0]

theorem hG2 : G2.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G2 L2 D2
  · intro i; fin_cases i <;> simp [D2] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G2, L2, D2, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- The bare square `σ₀`, as its Gram form. -/
def sigma0 (x : Fin 1 → ℚ) : ℚ := (mon0 x) ⬝ᵥ (G0 *ᵥ (mon0 x))

/-- The localizing multipliers, `sigma i` pairing with `g i`. -/
def sigma : Fin 2 → (Fin 1 → ℚ) → ℚ := ![fun x => (mon1 x) ⬝ᵥ (G1 *ᵥ (mon1 x)), fun x => (mon2 x) ⬝ᵥ (G2 *ᵥ (mon2 x))]

theorem hsigma0 : ∀ x, 0 ≤ sigma0 x := sos_nonneg G0 mon0 hG0

theorem hsigma : ∀ i x, 0 ≤ sigma i x := by
  intro i
  fin_cases i
  · exact sos_nonneg G1 mon1 hG1
  · exact sos_nonneg G2 mon2 hG2

/-- The Putinar identity, closed by `ring` in the free variable `x`. -/
theorem sos_identity : ∀ x, p x - (-2) = sigma0 x + ∑ i, sigma i x * g i x := by
  intro x
  simp only [p, g, sigma0, sigma, mon0, mon1, mon2, G0, G1, G2, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]
  ring

/-- Certified lower bound — on the feasible set, not on all of ℚⁿ. -/
theorem constrained_lb : ∀ x : Fin 1 → ℚ, (∀ i, 0 ≤ g i x) → (-2) ≤ p x :=
  constrained_lower_bound_of_sos p (-2) g sigma sigma0 hsigma0 hsigma sos_identity

/-- The candidate minimizer (cert.candidate.x); untrusted, checked below. -/
def xstar : Fin 1 → ℚ := ![1]

/-- `xstar` is in the feasible set — the half a bound alone never gives. -/
theorem xstar_feasible : ∀ i, 0 ≤ g i xstar := by
  intro i
  fin_cases i <;> norm_num [g, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

/-- The bound is attained here — an equation over ℚ, with no tolerance. -/
theorem attains : p xstar = (-2) := by
  norm_num [p, xstar]

/-- Certified constrained global minimum (cert.verdict). -/
theorem constrained_min : (∀ i, 0 ≤ g i xstar) ∧ ∀ x : Fin 1 → ℚ, (∀ i, 0 ≤ g i x) → p xstar ≤ p x :=
  constrained_min_of_sos_attained p (-2) g sigma sigma0 xstar hsigma0 hsigma sos_identity xstar_feasible attains

end PounceLean.CertifySOSBox
