/-
  POUNCE Lean certificate — generated proof (infeasible).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = infeasible
  problem_class = qp-convex
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Proves the constraint system A x ≥ b has NO solution, via the Farkas
  witness y ≥ 0 with Aᵀy = 0 and b·y > 0. No candidate point and no
  tolerance are involved — the three conditions hold exactly over ℚ.
-/
import Mathlib
import PounceLean.ConvexQP
import PounceLean.Farkas

namespace PounceLean.CertifyInfeasible

open Matrix

-- Resource limits, NOT soundness controls. Raising a budget cannot make a
-- false proof pass; the kernel still checks every step. (`native_decide`
-- WOULD cost trust — it adds an axiom — and is deliberately not used.)
--
-- The default 200000-heartbeat budget is far too small for a realistic
-- problem: netlib afiro (n=32) needs ~10^7, i.e. ~50x the default and
-- roughly 8 minutes. Measured ladder: 400k/800k/1.6M/3.2M/6.4M all fail,
-- 12.8M passes at 461s, with time scaling linearly in the budget — the
-- tactic consumes whatever it is given rather than converging early.
--
-- So no constant is right for the next problem up. Heartbeats proxy WORK;
-- what needs bounding is WALL CLOCK, so that CI cannot hang. That is the
-- job of an external `timeout`, which scripts/check-lean-cert.sh applies.
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open PounceLean.ConvexQP (Feasible)

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "c2ce4026a4f1338b8996f8603ad6b07604125613201b1e39ac3f0ae134b45347"
def solSha256 : String := "6ed24301b237c2ce4191e96726b53cb10fa5bb20b63c6b55a62f39364f77b20f"

def Amat : Matrix (Fin 3) (Fin 2) ℚ := !![1, 1; -1, 0; 0, -1]
def bvec : Fin 3 → ℚ := ![2, 0, 0]

-- Farkas witness (cert.witnesses.farkas); untrusted — checked below.
def yvec : Fin 3 → ℚ := ![1, 1, 1]

theorem hy_nonneg : ∀ i, 0 ≤ yvec i := by
  intro i
  fin_cases i <;> norm_num [yvec]

theorem hAty : Amatᵀ *ᵥ yvec = 0 := by
  funext i
  fin_cases i <;> simp [Amat, yvec, transpose, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

theorem hby : 0 < bvec ⬝ᵥ yvec := by
  simp [bvec, yvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- The system `A x ≥ b` has no solution (cert.verdict = infeasible). -/
theorem infeasible : ¬ ∃ x : Fin 2 → ℚ, Feasible Amat bvec x :=
  PounceLean.Farkas.infeasible_of_farkas Amat bvec yvec hy_nonneg hAty hby

/-- Per-point corollary: no specific `x` is feasible. -/
theorem no_point_feasible (x : Fin 2 → ℚ) : ¬ Feasible Amat bvec x :=
  PounceLean.Farkas.not_feasible_of_farkas Amat bvec yvec hy_nonneg hAty hby x

end PounceLean.CertifyInfeasible
