/-
  POUNCE Lean certificate — generated proof (unbounded).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = unbounded
  problem_class = qp-convex
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Proves the objective is unbounded below on the feasible set: for every
  bound M there is a feasible point with objective < M. Two witnesses are
  required — a feasible x0 and a recession direction d — because a
  direction alone cannot distinguish this from an empty feasible set.
-/
import Mathlib
import PounceLean.ConvexQP
import PounceLean.Unbounded

namespace PounceLean.CertifyUnbounded

open Matrix
open PounceLean.ConvexQP (obj Feasible)

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "3a6c933d79c231c566f3efa5c634fef6583ec27b3dcadb52b100769745ecc75b"
def solSha256 : String := "4870cf3f245456cdf6503925e075fcd21fd879aa4f132c9e1970f105f01c4d5a"

def Qmat : Matrix (Fin 2) (Fin 2) ℚ := !![0, 0; 0, 0]
def cvec : Fin 2 → ℚ := ![-1, -1]
def kconst : ℚ := 0
def Amat : Matrix (Fin 1) (Fin 2) ℚ := !![1, 1]
def bvec : Fin 1 → ℚ := ![1]

-- recession witnesses (cert.witnesses.recession); untrusted — checked below
def xzero : Fin 2 → ℚ := ![1755237233921853 / 8796093022208, 438809890021405 / 2199023255552]
def dvec  : Fin 2 → ℚ := ![1755237233921853 / 8796093022208, 438809890021405 / 2199023255552]

theorem hQsymm : Qmatᵀ = Qmat := by
  funext i j
  fin_cases i <;> fin_cases j <;> simp [Qmat, transpose, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

theorem hfeas : Feasible Amat bvec xzero := by
  intro i
  fin_cases i <;> simp [Feasible, Amat, bvec, xzero, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

theorem hQd : Qmat *ᵥ dvec = 0 := by
  funext i
  fin_cases i <;> simp [Qmat, dvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

theorem hAd : ∀ i, 0 ≤ (Amat *ᵥ dvec) i := by
  intro i
  fin_cases i <;> simp [Amat, dvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

theorem hcd : cvec ⬝ᵥ dvec < 0 := by
  simp [cvec, dvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- The objective is unbounded below on the feasible set. -/
theorem unbounded :
    ∀ M : ℚ, ∃ x : Fin 2 → ℚ, Feasible Amat bvec x ∧ obj Qmat cvec kconst x < M :=
  PounceLean.Unbounded.unbounded_of_recession
    Qmat cvec kconst Amat bvec xzero dvec hQsymm hfeas hQd hAd hcd

end PounceLean.CertifyUnbounded
