/-
  POUNCE Lean certificate — generated proof (local minimum, Putinar SOS).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = local-min
  problem_class = sos-poly
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Certifies  γ ≤ p(x)  at every FEASIBLE x WITHIN THE BALL below, with γ = -5,
  via  p(x) − γ = σ₀(x) + Σᵢ σᵢ(x)·gᵢ(x) + σ_B(x)·(r² − ‖x − c‖²)
  and every σ a PSD Gram form. The bound holds on that set only — weaker
  than an unconstrained SOS bound, and also far more widely available:
  `p − γ` need only be a sum of squares MODULO the constraints.

  The ball is a constraint like any other here; nothing about the proof
  knows it is a neighborhood. What that buys is reach: at a local
  minimum that is not global the unrestricted claim is FALSE, so no
  certificate for it exists at any relaxation order, while restricted
  to the ball the claim is both true and easier to certify.

  The bound is ATTAINED at the exhibited xstar, itself proved to lie in
  the set the bound is about, so it is the local minimum.
-/
import Mathlib
import PounceLean.PSD
import PounceLean.SOS

namespace PounceLean.CertifySOSLocal

open Matrix
open PounceLean.SOS (sos_nonneg sqdist local_lower_bound_of_sos local_min_of_sos_attained)

set_option maxHeartbeats 0
set_option maxRecDepth 100000

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "605303b0378b1c04bb3c6c147de48a94d520683ca626cdea3cb0a93e2d9f7f48"
def solSha256 : String := "61dc49849efb63d47f394706e1a3002ab69d53c2b9768cf4d065b6d5b6e752d9"

/-- Objective (cert.problem.polynomial), possibly nonconvex. -/
def p (x : Fin 1 → ℚ) : ℚ := (-12) * (x 0) ^ 2 + (4) * (x 0) ^ 3 + (3) * (x 0) ^ 4

/-- The feasible set `gᵢ(x) ≥ 0` (cert.problem.poly_constraints). -/
def g : Fin 0 → (Fin 1 → ℚ) → ℚ := ![]

/-- Centre of the neighborhood the claim is about (cert.problem.neighborhood). -/
def center : Fin 1 → ℚ := ![1]

/-- Its radius, SQUARED — ℚ is not closed under square roots. -/
def rsq : ℚ := 1

/-- The ball is not a point: without this the claim below would hold
vacuously wherever `rsq < 0`, and say nothing where `rsq = 0`. -/
theorem radius_pos : (0:ℚ) < rsq := by norm_num [rsq]

-- σ₀ — the bare square. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon0 (x : Fin 1 → ℚ) : Fin 3 → ℚ := ![1, (x 0) ^ 1, (x 0) ^ 2]
def G0 : Matrix (Fin 3) (Fin 3) ℚ := !![5, -3 / 2, -7 / 2; -3 / 2, 5 / 2, -1; -7 / 2, -1, 9 / 2]
def L0 : Matrix (Fin 3) (Fin 3) ℚ := !![1, 0, 0; -3 / 10, 1, 0; -7 / 10, -1, 1]
def D0 : Fin 3 → ℚ := ![5, 41 / 20, 0]

theorem hG0 : G0.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G0 L0 D0
  · intro i; fin_cases i <;> simp [D0] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G0, L0, D0, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

-- σ_B, multiplying the ball `rsq - sqdist x center`. Gram witness and LDLᵀ factors; untrusted, checked below.
def mon1 (x : Fin 1 → ℚ) : Fin 2 → ℚ := ![1, (x 0) ^ 1]
def G1 : Matrix (Fin 2) (Fin 2) ℚ := !![3 / 2, -3 / 2; -3 / 2, 3 / 2]
def L1 : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; -1, 1]
def D1 : Fin 2 → ℚ := ![3 / 2, 0]

theorem hG1 : G1.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G1 L1 D1
  · intro i; fin_cases i <;> simp [D1] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G1, L1, D1, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- The bare square `σ₀`, as its Gram form. -/
def sigma0 (x : Fin 1 → ℚ) : ℚ := (mon0 x) ⬝ᵥ (G0 *ᵥ (mon0 x))

/-- The localizing multipliers, `sigma i` pairing with `g i`. -/
def sigma : Fin 0 → (Fin 1 → ℚ) → ℚ := ![]

/-- `σ_B`, the ball's multiplier. -/
def sigmaB (x : Fin 1 → ℚ) : ℚ := (mon1 x) ⬝ᵥ (G1 *ᵥ (mon1 x))

theorem hsigma0 : ∀ x, 0 ≤ sigma0 x := sos_nonneg G0 mon0 hG0

theorem hsigma : ∀ i x, 0 ≤ sigma i x := fun i => i.elim0

theorem hsigmaB : ∀ x, 0 ≤ sigmaB x := sos_nonneg G1 mon1 hG1

/-- The Putinar identity, closed by `ring` in the free variable `x`. -/
theorem sos_identity : ∀ x, p x - (-5) = sigma0 x + (∑ i, sigma i x * g i x) + sigmaB x * (rsq - sqdist x center) := by
  intro x
  simp only [p, g, sigma0, sigma, mon0, mon1, G0, G1, sigmaB, sqdist, center, rsq, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]
  ring

/-- Certified lower bound — on the feasible set INTERSECTED WITH the ball.
Outside it this says nothing, and for a local minimum that is not global,
nothing is all that is true. -/
theorem local_lb : ∀ x : Fin 1 → ℚ, (∀ i, 0 ≤ g i x) → sqdist x center ≤ rsq → (-5) ≤ p x :=
  local_lower_bound_of_sos p (-5) g sigma sigma0 sigmaB center rsq hsigma0 hsigma hsigmaB sos_identity

/-- The candidate minimizer (cert.candidate.x); untrusted, checked below. -/
def xstar : Fin 1 → ℚ := ![1]

/-- `xstar` is in the feasible set — the half a bound alone never gives. -/
theorem xstar_feasible : ∀ i, 0 ≤ g i xstar := fun i => i.elim0

/-- …and inside the ball. A point that attains the bound from outside
the neighborhood would say nothing about the neighborhood. -/
theorem xstar_in_ball : sqdist xstar center ≤ rsq := by
  norm_num [sqdist, xstar, center, rsq, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

/-- The bound is attained here — an equation over ℚ, with no tolerance. -/
theorem attains : p xstar = (-5) := by
  norm_num [p, xstar]

/-- Certified LOCAL minimum (cert.verdict): no feasible point of the
neighborhood beats xstar. This is silent about points outside it — and
for this problem that silence is load-bearing, not a weakness of the
method. -/
theorem local_min : ((∀ i, 0 ≤ g i xstar) ∧ sqdist xstar center ≤ rsq) ∧ ∀ x : Fin 1 → ℚ, (∀ i, 0 ≤ g i x) → sqdist x center ≤ rsq → p xstar ≤ p x :=
  local_min_of_sos_attained p (-5) g sigma sigma0 sigmaB center rsq xstar
    hsigma0 hsigma hsigmaB sos_identity xstar_feasible xstar_in_ball attains

end PounceLean.CertifySOSLocal
