/-
  POUNCE Lean certificate — generated proof (global minimum, SOS).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = global-min
  problem_class = sos-poly
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Certifies  γ ≤ p(x)  for every x, with γ = 1, via
  p(x) − γ = m(x)ᵀ G m(x) and G ⪰ 0. No convexity is assumed: this is a
  global bound for a possibly NONCONVEX polynomial, which is exactly what
  a KKT argument cannot deliver.

  The bound is ATTAINED at the exhibited xstar, so it is the global
  minimum: no point anywhere does better, and this one achieves it.
-/
import Mathlib
import PounceLean.PSD
import PounceLean.SOS

namespace PounceLean.CertifySOS

open Matrix
open PounceLean.SOS (global_lower_bound_of_sos global_min_of_sos_attained)

set_option maxHeartbeats 0
set_option maxRecDepth 100000

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "69ee731038777d1c5b26b0ada4191a93d11dd91b10d427a0e7a16d2da01946d8"
def solSha256 : String := "ff379f9e3437895a5af918b6e01e71a6c7742795bc710689f10a05ee4bb9ff49"

/-- Objective (cert.problem.polynomial), possibly nonconvex. -/
def p (x : Fin 1 → ℚ) : ℚ := (2) + (-2) * (x 0) ^ 2 + (x 0) ^ 4

/-- Monomial lift (cert.witnesses.sos[0].monomials). -/
def mon (x : Fin 1 → ℚ) : Fin 3 → ℚ := ![1, (x 0) ^ 1, (x 0) ^ 2]

-- Gram witness and its LDLᵀ factors; untrusted, checked below.
def G : Matrix (Fin 3) (Fin 3) ℚ := !![1, 0, -1; 0, 0, 0; -1, 0, 1]
def Lmat : Matrix (Fin 3) (Fin 3) ℚ := !![1, 0, 0; 0, 1, 0; -1, 0, 1]
def Dvec : Fin 3 → ℚ := ![1, 0, 0]

theorem hG_psd : G.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL G Lmat Dvec
  · intro i; fin_cases i <;> simp [Dvec] <;> norm_num
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [G, Lmat, Dvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- The SOS identity, closed by `ring` in the free variable `x`. -/
theorem sos_identity : ∀ x, p x - (1) = (mon x) ⬝ᵥ (G *ᵥ (mon x)) := by
  intro x
  simp only [p, mon, G, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]
  ring

/-- Certified global lower bound. -/
theorem global_lb : ∀ x : Fin 1 → ℚ, (1) ≤ p x :=
  global_lower_bound_of_sos p (1) G mon hG_psd sos_identity

/-- The candidate minimizer (cert.candidate.x); untrusted, checked below. -/
def xstar : Fin 1 → ℚ := ![1]

/-- The bound is attained here — an equation over ℚ, with no tolerance. -/
theorem attains : p xstar = (1) := by
  norm_num [p, xstar]

/-- Certified global minimum (cert.verdict). -/
theorem global_min : ∀ x : Fin 1 → ℚ, p xstar ≤ p x :=
  global_min_of_sos_attained p (1) G mon xstar hG_psd sos_identity attains

end PounceLean.CertifySOS
