/-
  POUNCE Lean certificate — generated proof.

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = global-min
  problem_class = qp-convex
  solver        = pounce 0.5.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

      minimize    f(x) = ½ xᵀQx + cᵀx + k   over  ℚ
      subject to  A x ≥ b  and  E x = d

  Q below is the objective Hessian-of-record (the ½-factor and, when the
  objective is not half-quadratic, the factor of 2 are folded into Q and D
  so that f(x) = ½ xᵀQx + cᵀx + k uniformly).
-/
import Mathlib
import PounceLean.PSD
import PounceLean.ConvexQP

namespace PounceLean.CertifyEq

open Matrix
open PounceLean.ConvexQP (obj FeasibleEq global_min_of_kkt_eq)

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "f83c4a3fbbfe2f9340754a00c93ec86b328627c6e8dd762f7765d3a4374fd5d3"
def solSha256 : String := "21403dab89a496897b301b9059ce4256a4fd3911249c742d4fb616921d8fb8ca"

/-! ### Problem data, transcribed from the certificate. -/

def Q : Matrix (Fin 2) (Fin 2) ℚ := !![2, 0; 0, 2]
def cvec : Fin 2 → ℚ := ![-2, -4]
def kconst : ℚ := 5
def Amat : Matrix (Fin 0) (Fin 2) ℚ := Matrix.of ![]
def bvec : Fin 0 → ℚ := ![]
def Emat : Matrix (Fin 1) (Fin 2) ℚ := !![1, 1]
def dvec : Fin 1 → ℚ := ![2]
def xstar : Fin 2 → ℚ := ![1 / 2, 3 / 2]
def lamv : Fin 0 → ℚ := ![]
def muv : Fin 1 → ℚ := ![-1]
def Lmat : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; 0, 1]
def Dvec : Fin 2 → ℚ := ![2, 2]

/-! ### KKT data discharged from the (untrusted) witnesses. -/

/-- `Q ⪰ 0` from the LDLᵀ witness (reusable `posSemidef_of_LDL`). -/
theorem hQ_psd : Q.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL Q Lmat Dvec
  · intro i; fin_cases i <;> simp [Dvec]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [Q, Lmat, Dvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

/-- Stationarity `Q x* + c = Aᵀ λ + Eᵀ μ`. -/
theorem hstat : Q *ᵥ xstar + cvec = Amatᵀ *ᵥ lamv + Ematᵀ *ᵥ muv := by
  funext i; fin_cases i <;>
    simp [Q, cvec, xstar, Amat, lamv, Emat, muv, transpose, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Dual feasibility `λ ≥ 0`. -/
theorem hdual : ∀ i, 0 ≤ lamv i := by
  intro i; fin_cases i <;> simp [lamv] <;> norm_num

/-- Complementarity `λᵢ ((A x*)ᵢ − bᵢ) = 0`. -/
theorem hcompl : ∀ i, lamv i * ((Amat *ᵥ xstar) i - bvec i) = 0 := by
  intro i; fin_cases i <;>
    simp [lamv, Amat, xstar, bvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Equality feasibility of the candidate `E x* = d` (exact over ℚ). -/
theorem hxeq : ∀ j, (Emat *ᵥ xstar) j = dvec j := by
  intro j; fin_cases j <;>
    simp [Emat, dvec, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-! ### Verdict. -/

/-- Sanity: reported objective value (cert.candidate.objective). -/
theorem candidate_objective : obj Q cvec kconst xstar = 1 / 2 := by
  simp [obj, Q, cvec, kconst, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Tier 1: the candidate is feasible (inequalities and equalities). -/
theorem candidate_feasible : FeasibleEq Amat bvec Emat dvec xstar := by
  refine ⟨?_, ?_⟩
  · intro i; fin_cases i <;>
      simp [Amat, bvec, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num
  · intro j; fin_cases j <;>
      simp [Emat, dvec, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Tier 3 (global): `x*` minimizes the objective over the feasible set,
    by instantiating the reusable convex-QP KKT theorem (cert.verdict). -/
theorem global_min :
    ∀ y : Fin 2 → ℚ, FeasibleEq Amat bvec Emat dvec y →
      obj Q cvec kconst xstar ≤ obj Q cvec kconst y :=
  fun y hy =>
    global_min_of_kkt_eq Q cvec kconst Amat bvec Emat dvec xstar lamv muv
      hQ_psd hstat hdual hcompl hxeq y hy

end PounceLean.CertifyEq
