/-
  POUNCE Lean certificate — generated proof.

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = global-min
  problem_class = qp-convex
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

      minimize    f(x) = ½ xᵀQx + cᵀx + k   over  ℚ
      subject to  A x ≥ b

  Q below is the objective Hessian-of-record (the ½-factor and, when the
  objective is not half-quadratic, the factor of 2 are folded into Q and D
  so that f(x) = ½ xᵀQx + cᵀx + k uniformly).
-/
import Mathlib
import PounceLean.PSD
import PounceLean.ConvexQP

namespace PounceLean.CertifyLP

open Matrix

-- Resource limits, NOT soundness controls. Raising a budget cannot make a
-- false proof pass; the kernel still checks every step. (`native_decide`
-- WOULD cost trust — it adds an axiom — and is deliberately not used.)
--
-- The default 200000-heartbeat budget is far too small for a realistic
-- problem: netlib afiro (n=32) needs ~10^7, i.e. ~50x the default and
-- roughly 8 minutes. Measured ladder: 400k/800k/1.6M/3.2M/6.4M all fail,
-- 12.8M passes at 461s, with time scaling linearly in the budget — the
-- tactic consumes whatever it is given rather than converging early.
--
-- So no constant is right for the next problem up. Heartbeats proxy WORK;
-- what needs bounding is WALL CLOCK, so that CI cannot hang. That is the
-- job of an external `timeout`, which scripts/check-lean-cert.sh applies.
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open PounceLean.ConvexQP (obj Feasible global_min_of_kkt)

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "15188e16ab31cebcc77791bc298735867145a98f4202cedf18e3e02a67f5d482"
def solSha256 : String := "540e625d45119f4b81f5fa5227b6163909349d2d48cfb782c33e4d8df7aca738"

/-! ### Problem data, transcribed from the certificate. -/

def Q : Matrix (Fin 2) (Fin 2) ℚ := !![0, 0; 0, 0]
def cvec : Fin 2 → ℚ := ![1, 1]
def kconst : ℚ := 0
def Amat : Matrix (Fin 2) (Fin 2) ℚ := !![1, 2; 2, 1]
def bvec : Fin 2 → ℚ := ![4, 4]
def xstar : Fin 2 → ℚ := ![4 / 3, 4 / 3]
def lamv : Fin 2 → ℚ := ![1 / 3, 1 / 3]
def Lmat : Matrix (Fin 2) (Fin 2) ℚ := !![1, 0; 0, 1]
def Dvec : Fin 2 → ℚ := ![0, 0]

/-! ### KKT data discharged from the (untrusted) witnesses. -/

/-- `Q ⪰ 0` from the LDLᵀ witness (reusable `posSemidef_of_LDL`). -/
theorem hQ_psd : Q.PosSemidef := by
  apply PounceLean.PSD.posSemidef_of_LDL Q Lmat Dvec
  · intro i; fin_cases i <;> simp [Dvec]
  · ext i j; fin_cases i <;> fin_cases j <;>
      simp [Q, Lmat, Dvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one]

/-- Stationarity `Q x* + c = Aᵀ λ`. -/
theorem hstat : Q *ᵥ xstar + cvec = Amatᵀ *ᵥ lamv := by
  funext i; fin_cases i <;>
    simp [Q, cvec, xstar, Amat, lamv, transpose, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Dual feasibility `λ ≥ 0`. -/
theorem hdual : ∀ i, 0 ≤ lamv i := by
  intro i; fin_cases i <;> simp [lamv] <;> norm_num

/-- Complementarity `λᵢ ((A x*)ᵢ − bᵢ) = 0`. -/
theorem hcompl : ∀ i, lamv i * ((Amat *ᵥ xstar) i - bvec i) = 0 := by
  intro i; fin_cases i <;>
    simp [lamv, Amat, xstar, bvec, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-! ### Verdict. -/

/-- Sanity: reported objective value (cert.candidate.objective). -/
theorem candidate_objective : obj Q cvec kconst xstar = 8 / 3 := by
  simp [obj, Q, cvec, kconst, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Tier 1: the candidate is feasible. -/
theorem candidate_feasible : Feasible Amat bvec xstar := by
  intro i; fin_cases i <;>
    simp [Feasible, Amat, bvec, xstar, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- Tier 3 (global): `x*` minimizes the objective over the feasible set,
    by instantiating the reusable convex-QP KKT theorem (cert.verdict). -/
theorem global_min :
    ∀ y : Fin 2 → ℚ, Feasible Amat bvec y → obj Q cvec kconst xstar ≤ obj Q cvec kconst y :=
  fun y hy =>
    global_min_of_kkt Q cvec kconst Amat bvec xstar lamv hQ_psd hstat hdual hcompl y hy

end PounceLean.CertifyLP
