/-
  POUNCE Lean certificate — generated proof (Tier 1: feasible).

  Auto-generated by codegen/gen_lean.py from a pounce.lean-cert/v1
  certificate. DO NOT EDIT BY HAND — regenerate from the certificate.

  verdict       = feasible
  problem_class = qp-convex
  solver        = pounce 0.9.0
  toolchain     = leanprover/lean4:v4.31.0 / fabf563a7c95a166b8d7b6efca11c8b4dc9d911f

  Declared tolerance ε = 1 / 25000000. The candidate x* satisfies every
  constraint to within ε (exact ℚ residuals); x* is NOT claimed optimal.
  A feasibility witness x̂ certifies that a genuine feasible point exists
  within ∞-distance ε of x* (linear constraints ⇒ the projection is exact).
-/
import Mathlib
import PounceLean.ConvexQP
import PounceLean.Feasible

namespace PounceLean.CertifyFeasible

open Matrix

-- Resource limits, NOT soundness controls. Raising a budget cannot make a
-- false proof pass; the kernel still checks every step. (`native_decide`
-- WOULD cost trust — it adds an axiom — and is deliberately not used.)
--
-- The default 200000-heartbeat budget is far too small for a realistic
-- problem: netlib afiro (n=32) needs ~10^7, i.e. ~50x the default and
-- roughly 8 minutes. Measured ladder: 400k/800k/1.6M/3.2M/6.4M all fail,
-- 12.8M passes at 461s, with time scaling linearly in the budget — the
-- tactic consumes whatever it is given rather than converging early.
--
-- So no constant is right for the next problem up. Heartbeats proxy WORK;
-- what needs bounding is WALL CLOCK, so that CI cannot hang. That is the
-- job of an external `timeout`, which scripts/check-lean-cert.sh applies.
set_option maxHeartbeats 0
set_option maxRecDepth 100000
open PounceLean.ConvexQP (FeasibleEq)
open PounceLean.Feasible (FeasibleWithin exists_feasible_near)

-- binding (cert.binding); embed so the verdict provably concerns these bytes
def nlSha256  : String := "1c2c9a75dcb7be12561930a9cd92d8fe15895d74e63a478bea2b0c86c367e26d"
def solSha256 : String := "e7c72ba56e5dac6e5b4473f8bd99ce1d93e7d872dd765c6f03e0b736eb97b5b0"

/-! ### Problem data + candidate, transcribed from the certificate. -/

def Amat : Matrix (Fin 6) (Fin 2) ℚ := !![1, 2; 2, 1; 1, 0; -1, 0; 0, 1; 0, -1]
def bvec : Fin 6 → ℚ := ![4, 4, 0, -3, 0, -3]
def Emat : Matrix (Fin 0) (Fin 2) ℚ := Matrix.of ![]
def dvec : Fin 0 → ℚ := ![]
def xstar : Fin 2 → ℚ := ![6004799456128869 / 4503599627370496, 6004799456128871 / 4503599627370496]
def eps : ℚ := 1 / 25000000
def xhat : Fin 2 → ℚ := ![4 / 3, 4 / 3]

/-! ### Verdict: ε-feasibility of the candidate (exact ℚ residuals). -/

/-- `x*` satisfies every constraint to within the declared tolerance `ε`. -/
theorem candidate_eps_feasible : FeasibleWithin Amat bvec Emat dvec eps xstar := by
  refine ⟨by norm_num [eps], ?_, ?_⟩
  · intro i; fin_cases i <;>
      simp [Amat, bvec, xstar, eps, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num
  · intro j; fin_cases j <;>
      simp only [Emat, dvec, xstar, eps, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;>
      (rw [abs_le]; constructor <;> norm_num)

/-! ### Existence: a genuine feasible point within ε of x*. -/

/-- The witness `x̂` is *exactly* feasible (linear ⇒ exact projection). -/
theorem witness_feasible : FeasibleEq Amat bvec Emat dvec xhat := by
  refine ⟨?_, ?_⟩
  · intro i; fin_cases i <;>
      simp [Amat, bvec, xhat, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num
  · intro j; fin_cases j <;>
      simp [Emat, dvec, xhat, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;> norm_num

/-- `x̂` lies within ∞-distance `ε` of the reported `x*`. -/
theorem witness_close : ∀ i, |xhat i - xstar i| ≤ eps := by
  intro i; fin_cases i <;>
    simp only [xhat, xstar, eps, mulVec, dotProduct, Matrix.mul_apply, Matrix.diagonal_apply, Matrix.transpose_apply, Matrix.vecMul_diagonal, Matrix.vecMul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_succ, Matrix.head_cons, Matrix.of_apply, Matrix.cons_val', Matrix.empty_val', Matrix.cons_val_fin_one] <;>
    (rw [abs_le]; constructor <;> norm_num)

/-- A genuine feasible point exists within ∞-distance `ε` of `x*`. -/
theorem feasible_point_exists :
    ∃ x : Fin 2 → ℚ, FeasibleEq Amat bvec Emat dvec x ∧ (∀ i, |x i - xstar i| ≤ eps) :=
  exists_feasible_near Amat bvec Emat dvec xstar eps xhat witness_feasible witness_close

end PounceLean.CertifyFeasible
