// The C runtime the POUNCE plugin emits into generated code.
//
// CasADi's `Function::generate()` turns a solver call into a self-contained
// `.c` file. For an `nlpsol` that means the whole solve, not just the model:
// the oracle functions are generated by CasADi, and this runtime is the loop
// that hands them to the solver. It is the counterpart of CasADi's
// `ipopt_runtime.hpp`, and deliberately close to it — both drive the same
// Ipopt-3.14 C API, which `pounce.h` reimplements.
//
// "Self-contained" here means no CasADi and no Python at run time. It does
// not mean no dependencies: the generated file includes `pounce.h` and links
// `libpounce_cinterface`, exactly as CasADi's generated Ipopt code includes
// `<coin-or/IpStdCInterface.h>` and links libipopt.
//
// This is plain C held in a string rather than a template header processed by
// CasADi's `sanitize_source` (which is how CasADi does its own): the plugin is
// built out of tree, with no build step to turn one into the other. What the
// generated file supplies around it is `casadi_real`, `casadi_int`, and the
// `casadi_nlpsol_prob` / `casadi_nlpsol_data` structures from `AUX_NLP`.

#ifndef POUNCE_CASADI_RUNTIME_HPP
#define POUNCE_CASADI_RUNTIME_HPP

namespace casadi {

  static const char* pounce_runtime_str = R"RUNTIME(
/* casadi::UnifiedReturnStatus, which is C++ and so not in scope here.
   CasADi's own runtimes substitute the same literals at generation time. */
#ifndef CASADI_SOLVER_RET_SUCCESS
#define CASADI_SOLVER_RET_SUCCESS 0
#define CASADI_SOLVER_RET_UNKNOWN 1
#define CASADI_SOLVER_RET_LIMITED 2
#endif

#if defined(__GNUC__) || defined(__clang__)
#define CASADI_POUNCE_UNUSED __attribute__((unused))
#else
#define CASADI_POUNCE_UNUSED
#endif

struct casadi_pounce_prob {
  const struct casadi_nlpsol_prob* nlp;
  const casadi_int *sp_h, *sp_a;
  casadi_int nnz_h, nnz_a;
  /* Nonlinear-variable subset for the limited-memory Hessian; 0 if none. */
  const ipindex* nonlin_vars;
  casadi_int n_nonlin_vars;
  /* Zero the multipliers of bounds this far from being active. A negative
     margin disables it — see `clip_inactive_lam`. */
  casadi_real inactive_lam_margin;
  Eval_F_CB eval_f;
  Eval_G_CB eval_g;
  Eval_Grad_F_CB eval_grad_f;
  Eval_Jac_G_CB eval_jac_g;
  Eval_H_CB eval_h;
};

struct casadi_pounce_data {
  const struct casadi_pounce_prob* prob;
  struct casadi_nlpsol_data* nlp;
  IpoptProblem pounce;
  const casadi_real** arg;
  casadi_real** res;
  casadi_int* iw;
  casadi_real* w;
  casadi_real *z_L, *z_U;
  enum ApplicationReturnStatus status;
  int unified_return_status;
  int success;
};

static void casadi_pounce_setup(struct casadi_pounce_prob* p) {
  if (p->sp_h) {
    p->nnz_h = p->sp_h[2+p->sp_h[1]];
  } else {
    p->nnz_h = 0;
  }
  p->nnz_a = p->sp_a[2+p->sp_a[1]];
}

CASADI_POUNCE_UNUSED static int pounce_init_mem(struct casadi_pounce_data* d) {
  (void)d;
  return 0;
}

CASADI_POUNCE_UNUSED static void pounce_free_mem(struct casadi_pounce_data* d) {
  (void)d;
}

CASADI_POUNCE_UNUSED static void casadi_pounce_work(const struct casadi_pounce_prob* p,
    casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w) {
  casadi_nlpsol_work(p->nlp, sz_arg, sz_res, sz_iw, sz_w);
  *sz_w += p->nlp->nx; /* z_L */
  *sz_w += p->nlp->nx; /* z_U */
}

static void casadi_pounce_init(struct casadi_pounce_data* d,
    const casadi_real*** arg, casadi_real*** res, casadi_int** iw, casadi_real** w) {
  const struct casadi_pounce_prob* p = d->prob;
  const struct casadi_nlpsol_prob* p_nlp = p->nlp;
  d->z_L = *w; *w += p_nlp->nx;
  d->z_U = *w; *w += p_nlp->nx;
  d->arg = *arg;
  d->res = *res;
  d->iw = *iw;
  d->w = *w;
}

static void casadi_pounce_presolve(struct casadi_pounce_data* d) {
  const struct casadi_pounce_prob* p = d->prob;
  const struct casadi_nlpsol_prob* p_nlp = p->nlp;
  const struct casadi_nlpsol_data* d_nlp = d->nlp;

  d->pounce = CreateIpoptProblem(
      (ipindex) p_nlp->nx, (ipnumber*) d_nlp->lbz, (ipnumber*) d_nlp->ubz,
      (ipindex) p_nlp->ng, (ipnumber*) d_nlp->lbz+p_nlp->nx,
                           (ipnumber*) d_nlp->ubz+p_nlp->nx,
      (ipindex) p->nnz_a, (ipindex) p->nnz_h, 0,
      p->eval_f, p->eval_g, p->eval_grad_f, p->eval_jac_g, p->eval_h);

  if (d->pounce && p->n_nonlin_vars > 0) {
    IpoptSetNonlinearVariables(d->pounce, (ipindex) p->n_nonlin_vars, p->nonlin_vars);
  }
}

static void casadi_pounce_solve(struct casadi_pounce_data* d) {
  const struct casadi_pounce_prob* p = d->prob;
  const struct casadi_nlpsol_prob* p_nlp = p->nlp;
  struct casadi_nlpsol_data* d_nlp = d->nlp;
  casadi_int i;

  d->unified_return_status = CASADI_SOLVER_RET_UNKNOWN;

  if (!d->pounce) {
    d->success = 0;
    return;
  }

  /* Split the signed bound multipliers the way the C API wants them. */
  for (i=0; i<p_nlp->nx; ++i) {
    d->z_L[i] = casadi_fmax(0., -d_nlp->lam[i]);
    d->z_U[i] = casadi_fmax(0., d_nlp->lam[i]);
  }

  d->status = IpoptSolve(d->pounce, d_nlp->z, d_nlp->z + p_nlp->nx,
                         &d_nlp->objective, d_nlp->lam+p_nlp->nx,
                         d->z_L, d->z_U, d);

  for (i=0; i<p_nlp->nx; ++i) {
    d_nlp->lam[i] = d->z_U[i]-d->z_L[i];
  }

  /* `clip_inactive_lam`, in the same place and with the same test as the
     interpreted plugin: a residual multiplier on a bound the solve never
     approached turns that variable's whole sensitivity row into zeros
     downstream, so it is zeroed here rather than passed on. */
  if (p->inactive_lam_margin >= 0) {
    for (i=0; i<p_nlp->nx+p_nlp->ng; ++i) {
      if (d_nlp->lam[i] > 0 &&
          d_nlp->ubz[i] - d_nlp->z[i] > p->inactive_lam_margin) d_nlp->lam[i] = 0;
      if (d_nlp->lam[i] < 0 &&
          d_nlp->z[i] - d_nlp->lbz[i] > p->inactive_lam_margin) d_nlp->lam[i] = 0;
    }
  }

  FreeIpoptProblem(d->pounce);
  d->pounce = 0;

  if (d->status==Solve_Succeeded ||
      d->status==Solved_To_Acceptable_Level ||
      d->status==Feasible_Point_Found) {
    d->unified_return_status = CASADI_SOLVER_RET_SUCCESS;
  } else if (d->status==Maximum_Iterations_Exceeded ||
             d->status==Maximum_CpuTime_Exceeded) {
    d->unified_return_status = CASADI_SOLVER_RET_LIMITED;
  }

  d->success = (d->unified_return_status == CASADI_SOLVER_RET_SUCCESS);
}

static void casadi_pounce_sparsity(const casadi_int* sp, ipindex *iRow, ipindex *jCol) {
  casadi_int ncol = sp[1];
  const casadi_int* colind = sp+2;
  const casadi_int* row = colind+ncol+1;
  casadi_int cc, el;
  for (cc=0; cc<ncol; ++cc) {
    for (el=colind[cc]; el<colind[cc+1]; ++el) {
      *iRow++ = (ipindex) row[el];
      *jCol++ = (ipindex) cc;
    }
  }
}

/* Upper-triangular CCS is lower-triangular triplet with row and column
   swapped, which is the order the C API asks for. */
CASADI_POUNCE_UNUSED static void casadi_pounce_sparsity_h(const casadi_int* sp, ipindex *iRow, ipindex *jCol) {
  casadi_int ncol = sp[1];
  const casadi_int* colind = sp+2;
  const casadi_int* row = colind+ncol+1;
  casadi_int cc, el;
  for (cc=0; cc<ncol; ++cc) {
    for (el=colind[cc]; el<colind[cc+1]; ++el) {
      *iRow++ = (ipindex) cc;
      *jCol++ = (ipindex) row[el];
    }
  }
}

CASADI_POUNCE_UNUSED static bool casadi_pounce_hess_l_empty(ipindex n, ipnumber *x, bool new_x,
    ipnumber obj_factor, ipindex m, ipnumber *lambda, bool new_lambda,
    ipindex nele_hess, ipindex *iRow, ipindex *jCol, ipnumber *values,
    UserDataPtr user_data) {
  (void)n; (void)x; (void)new_x; (void)obj_factor; (void)m; (void)lambda;
  (void)new_lambda; (void)nele_hess; (void)iRow; (void)jCol; (void)values;
  (void)user_data;
  return false;
}
)RUNTIME";

} // namespace casadi

#endif // POUNCE_CASADI_RUNTIME_HPP
