"""Type stub for the pounce_studio_mcp._native PyO3 extension.

Mirrors the surface area of `crates/pounce-studio-pyo3/src/lib.rs`.
All analysis methods return JSON-encoded strings; callers typically go
through `reports.py` which `json.loads()` them into Python dicts.
"""
from __future__ import annotations

__version__: str
SOLVE_REPORT_SCHEMA: str

class Report:
    @staticmethod
    def from_bytes(bytes: bytes) -> Report: ...
    @staticmethod
    def from_path(path: str) -> Report: ...
    def summarize(self) -> str: ...
    def convergence_trace(self) -> str: ...
    def find_stalls(
        self,
        min_window: int | None = ...,
        max_log10_progress: float | None = ...,
    ) -> str: ...
    def restoration_windows(self) -> str: ...
    def diagnose(self) -> str: ...
    def get_iterate(self, k: int) -> str: ...
    def render_markdown(self) -> str: ...

class IterDump:
    @staticmethod
    def from_bytes(bytes: bytes) -> IterDump: ...
    @staticmethod
    def from_path(path: str) -> IterDump: ...
    def header(self) -> str: ...
    def records(self) -> str: ...
    def record_count(self) -> int: ...

def compare_reports(pairs: list[tuple[str, Report]]) -> str: ...
