#!/usr/bin/env python3
"""Three conveniences a CasADi user reaches for once the model is real.

1. **Your own derivative functions.** `grad_f`, `jac_g` and `hess_lag`
   replace the ones CasADi generates from the graph — for a hand-derived
   Jacobian, a codegen'd one, or anything cheaper than differentiating
   the expression.

2. **Convexifying the Lagrangian Hessian.** `convexify_strategy` reshapes
   the Hessian's spectrum before the solver sees it. This is CasADi's own
   `Convexify` — the same code its ipopt plugin uses — so a model tuned
   against `ipopt` behaves the same way here. It changes *which* local
   minimum a nonconvex problem walks to, so it is a modelling decision,
   not a tolerance.

3. **Saving the solver.** `save` / `load` round-trip an `nlpsol`, so a
   configured solver can be built once and shipped. Reading it back needs
   the plugin loadable in that process (`import pounce_casadi`, or the
   plugin on CasADi's search path).
"""

import os
import tempfile

import casadi as ca

QUIET = {"pounce": {"print_level": 0}, "print_time": False}


# ---------------------------------------------------------------- 1.
print("1. user-supplied derivatives")

x = ca.MX.sym("x", 2)
p = ca.MX.sym("p")
lam_f = ca.MX.sym("lam_f")
lam_g = ca.MX.sym("lam_g")

f = (1 - x[0]) ** 2 + 100 * (x[1] - x[0] ** 2) ** 2
g = x[0] ** 2 + x[1] ** 2 - p
nlp = {"x": x, "p": p, "f": f, "g": g}
kw = dict(x0=[0.5, 0.5], p=1.5, lbg=-ca.inf, ubg=0)

# Here they are still built symbolically — the point is that the plugin
# takes whatever `Function` you hand it, including a compiled one.
mine = {
    "grad_f": ca.Function("my_grad_f", [x, p], [f, ca.gradient(f, x)]),
    "jac_g": ca.Function("my_jac_g", [x, p], [g, ca.jacobian(g, x)]),
    # Note the shape contract: upper triangular, and the objective carries
    # its own multiplier `lam_f`.
    "hess_lag": ca.Function(
        "my_hess_l", [x, p, lam_f, lam_g],
        [ca.triu(ca.hessian(lam_f * f + lam_g * g, x)[0])]),
}

auto = ca.nlpsol("auto", "pounce", nlp, QUIET)(**kw)
custom = ca.nlpsol("custom", "pounce", nlp, dict(QUIET, **mine))(**kw)
print(f"   autogenerated  x = {auto['x'].full().ravel()}")
print(f"   user-supplied  x = {custom['x'].full().ravel()}")
print(f"   difference       = {float(ca.norm_inf(auto['x'] - custom['x'])):.3e}")

# A wrong signature is caught when the solver is built, not at the first
# evaluation with a corrupt read.
try:
    ca.nlpsol("bad", "pounce", nlp,
              dict(QUIET, grad_f=ca.Function("bad", [x], [ca.gradient(f, x)])))
except RuntimeError as exc:
    print(f"   wrong shape refused: {str(exc).strip().splitlines()[-1][:60]}…")


# ---------------------------------------------------------------- 2.
print("\n2. convexify_strategy on a nonconvex objective")

y = ca.MX.sym("y", 3)
wiggly = {"x": y, "f": ca.sum1(ca.sin(3 * y)) + 0.5 * ca.sumsqr(y - 0.3),
          "g": ca.sum1(y)}
kw2 = dict(x0=[0.4, 0.1, -0.2], lbg=-1, ubg=1)

for strategy in ("none", "eigen-clip", "eigen-reflect"):
    opts = dict(QUIET)
    if strategy != "none":
        opts["convexify_strategy"] = strategy
    S = ca.nlpsol("S", "pounce", wiggly, opts)
    r = S(**kw2)
    print(f"   {strategy:<14s} f = {float(r['f']):+.6f}  "
          f"in {S.stats()['iter_count']:2d} iterations")

print("   (eigen-reflect walks to a different — here better — local minimum;")
print("    CasADi's ipopt plugin does exactly the same on this model.)")


# ---------------------------------------------------------------- 3.
print("\n3. save / load")

configured = ca.nlpsol("configured", "pounce", nlp, dict(
    QUIET, clip_inactive_lam=True, var_string_md={"names": ["x0", "x1"]}))
before = configured(**kw)

with tempfile.TemporaryDirectory() as d:
    path = os.path.join(d, "solver.casadi")
    configured.save(path)
    print(f"   wrote {os.path.getsize(path)} bytes")
    reloaded = ca.Function.load(path)

after = reloaded(**kw)
print(f"   before  x = {before['x'].full().ravel()}")
print(f"   after   x = {after['x'].full().ravel()}")
print(f"   identical: {float(ca.norm_inf(before['x'] - after['x'])) == 0.0}")
print(f"   options survived: {reloaded.stats()['var_string_md']}")
print("   (configuration crosses; per-solve state — including a working set")
print("    carried under warm_start_from_previous — does not.)")
